apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ky0108k5m-dotnet-basic
  janus-idp.io/tekton: ky0108k5m-dotnet-basic
  backstage.io/kubernetes-id: ky0108k5m-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ky0108k5m-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
